import Pkg
Pkg.add("Statistics")
Pkg.add("LinearAlgebra")
Pkg.add("Dates")
Pkg.add("PyCall")
Pkg.add("NPZ")
Pkg.add("DelimitedFiles")
Pkg.add("NumericalIntegration")
Pkg.add("BasicInterpolators")
Pkg.add("Plots")
Pkg.add("ColorSchemes")
